### ISSUE TITLE
Initialization crash with new version

### ISSUE THREAD

**Issue by CherryBella** [VoidArkana/MarvelousMenagerie#2]
Whenever I try to open up the game with the new update of Menagerie it crashes and keeps giving me the same error. I attached the crash log to see if you can figure out the problem, it seems to be something with UP but I have no idea what it is. 

[crash-2024-07-18_01.39.24-client.txt](https://github.com/user-attachments/files/16278342/crash-2024-07-18_01.39.24-client.txt)

**Comment by VoidArkana** [comment]
it seems you're somehow using unusual prehistory version 1.6? I'm not sure where you got that file from, but Marvelous Menagerie works with with the latest public version of Unusual Prehistory available, so try downgrading to Unusual Prehistory 1.5.0.3
