### ISSUE TITLE
Bonemealing prototaxites causes crashes

### ISSUE THREAD

**Issue by CherryBella** [VoidArkana/MarvelousMenagerie#3]
Any time I've tried to use bone meal on a prototaxite it will freeze the game after one bone meal and then promptly crash it. Returning to the world reveals that the prototaxite turns into a couple of its blocks but not anywhere near the final giant form it's supposed to be.

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState net.minecraftforge.event.ForgeEventFactory.alterGround(net.minecraft.world.level.LevelSimulatedReader, net.minecraft.util.RandomSource, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState)'

[crash-2024-07-28_21.50.04-server.txt](https://github.com/user-attachments/files/16406219/crash-2024-07-28_21.50.04-server.txt)

**Comment by VoidArkana** [comment]
It seems that particular feature is not compatible with NeoForge, at least that version of, because of the way it's written it accesses some Forge methods, unfortunately it's something I cannot fix so for now I will have to mark that MM does not fully support Neoforge
